progress/JSDO

src/SSOtests/authenticateTest.js, src/SSOtests/index.html, src/SSOtests/newAPItest.html, src/SSOtests/newAPItest.js, src/SSOtests/outputMsgs.js, src/progress.auth.js, src/progress.js, src/progress.session.js
Alright, this should work this time.
=> Featureauthprovider

src/SSOtests/eLogout-0LengthToken.html, src/SSOtests/eLogout-BadToken.html, src/SSOtests/eLogout-ExpiredToken.html, src/SSOtests/eLogout-NoToken.html, src/progress.session.js
Code reviewed by Edsel Garcia and checked into ClearQuest. Accidentally merged into master branch on May 12 and reverted May 13. Let me see if I can do it right this time!
=> send token on logout if using SSO

src/progress.session.js
Adding getSession() code to the page refresh story.
=> Story getsession

src/progress.session.js
combined page refresh and getSession and Edsel's changes that were checked directly into ClearCase
=> Page refresh

src/progress.session.js
Edsel already reviewed this -- I asked him to do ti because he had been involved in originally logging the bug.
=> fixed the way jsessionid is added to URIs

src/progress.js, src/progress.session.js
Added a fix where we check to make sure we are connected before calling addCatalog().
=> Added a check to make sure we are connected before

src/progress.session.js
Session objects that did not use authProviders were being prevented from
logging in.
=> Added a fix for TP73061

src/auth/progress.auth.form.js, src/progress.session.js
Added two fixes:
1. Adds encoding to user input so we accept weird characters.
2. Fixes the login bug since isAuthorized() shouldn't depend on loginResult anymore since we don't call login() on the JSDOSession anymore.
=> Added the two fixes

src/progress.js
Included the fix for TP78242 issue in JSDO 4.4.1 branch
=> Fix for TP78242 fill failure promise in JSDO 4.4.1 branch

src/progress.js, src/progress.session.js
Added invalidate() and added the changes to pull request,
=> Story invalidate

packages/ng-datasource/src/progress.data.ng.ds.ts, src/progress.js
This includes changes related to JSDO and DataSource to support 'Continuous Scrolling' in NativeScript mobile app which uses JSDO internally
=> Support for Continuous scrolling - JSDO and DataSource changes

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
Adding typings file and the transpiled JavaScript code for DataSource
=> Adding typings file and the transpiled JavaScript code for DataSource

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts
Updated error handling.
Updated read() so it now has copy of jsdo data
=> Updated error handling, read() now has copy of data

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
- [x ] See our contributing guidelines: https://github.com/progress/JSDO/blob/master/contributing.md#contribute-to-the-code-base.
findbyid() removal of copyRecord is an optimization made possible from changes in read() API.
changing getData to return an Array<object> is the correct typing description of the actual behavior.  also now returns local copy datasource data as this is what the function is intended for.
ADAS 1858/1859 getData(): Array<object>, remove _copyRecord from findById(), updated typings, updated internal wiki.
=> getData() : Array<object> and return local data , findById() no copy, updated typings

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
=> Miko adas1858/1859 find by id() no copy and get data() return array obj

src/progress.util.js
Added back code to load dependencies.
Code now uses an expression with "" which disables the check with webpack.
=> Adas 1791/remove webpack warnings

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
=> Revert "getData() : Array<object> and return local data , findById() no copy, updated typings"

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
=> Revert "Miko adas1858/1859 find by id() no copy and get data() return array obj"

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts
remove use of _data as discussed. change getdata to Array<object> as planned
=> Miko adas 2034 remove  data var 

packages/ng-datasource/typings/progress.data.ng.ds.d.ts
=> fix typings file

.gitignore, packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
Update DataSource:
1.) added readLocal property
2.) jsdo.autoApplyChanges now = true
3.) removed ()acceptChanges and cancelChanges()
=> Maura hier support2

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts
changing getData to use getJsdoData which makes a copy and handles cases for child datasource
=> update getData to make copy and handle heir changes

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts, typings/progress.all.d.ts
Implementation to support Server-side operations in KUIB via Datasource. Changes include
Datasource
Typings and Transpiled version of Datasource
=> Implementation to support Server-side operations in KUIB via Datasource

typings/progress.all.d.ts
=> Changed JSDOSessionPingInfo to JSDOSessionInfo

packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
Removed **pageSize** and changed the types of **top** and **skip** properties in DataSourceOptions
=> Anil/remove pageSize and refactor types

src/progress.js, src/progress.session.js
Changed info to be an object instead of an array in Promise callback for getSession() addCatalog().
=> Changed info to be an object instead of array

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
Handled scenarios where search and scroll is perpetual in the template via Data Source changes (by handling empty resultset)
=> Anil/ADAS-2100 - Datasource changes

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts
Fixing DataSource.read() to properly handle param object when it is empty, i.e no properties specified
=> Maura data source read adas 2226

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts
Changed code to use result.request.response instead of result.request.xhr.response.
=> Changed code to use result.request.response

package.json, packages/angular/package.json, packages/core/package.json, packages/nativescript/package.json, packages/ng-datasource/package.json, packages/node/package.json
Updated all of JSDO packages to next JSDO version (5.0.1)
=> Anil/update packages with 5.0.1

src/progress.data.kendo.js, src/progress.js, src/progress.util.js
Added code to DataSource transport to ensure usage of server-side idProperty when using idProperty definition.
=> EG/adas 1562/support id property

package.json
=> adjustments for build configurations

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts
Changed DataSource code to use result.request.batch instead of result.info.batch.
=> Changed info.batch to request.batch

.gitignore, package.json, test-services/Sports/Customer.cls, test-services/Sports/customer.i, test/smoke.invoke.js
Added dependencies needed for running Mocha/Chai tests for the JSDO.
=> Add packages needed for Mocha/Chai testing

typings/progress.all.d.ts
Added better typings for fill() and read().
=> Added types for fill()/read()

packages/ng-datasource/src/progress.data.ng.ds.js, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts
A new API 'normalizedErrorObj' has been implemented. and this will return valid error object with 'info'  followed by xhr information in it.
=> Adding fix for bug - ADAS-9502 - Return error object from Datasource

packages/angular/package.json, packages/core/package.json, packages/nativescript/package.json, packages/ng-datasource/package.json, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/ng-datasource/typings/progress.data.ng.ds.d.ts, packages/node/package.json
=> Adas 2304 upgrade rxjs

packages/node/test/regressions/ADAS-7282.js, packages/node/test/smoke.datasource.js
Updated tests in jsdo-node package to use a service running in Docker container instead of using a service running in oemobiledemo machine.
=> Anil/adas 8909/mocha tests

src/progress.session.js
=> fix to handle timeout

src/progress.session.js
=> Revert "fix to handle timeout"

lib/progress.all.js, lib/progress.all.min.js, lib/progress.jsdo.js, lib/progress.jsdo.min.js, package.json, packages/angular/package.json, packages/core/package.json, packages/core/readme.md, packages/nativescript/package.json, packages/ng-datasource/package.json, packages/ng-datasource/src/progress.data.ng.ds.ts, packages/node/package.json, readme.md, src/auth/progress.auth.basic.js, src/auth/progress.auth.form.js, src/auth/progress.auth.js, src/auth/progress.auth.sso.js, src/progress.data.kendo.js, src/progress.js, src/progress.session.js, src/progress.util.js
ADAS-7344 update jsdo to next version as part of end game tasks.  This will not be merged until develop is merged to master for 6.0.0.
=> update JSDO to next version as part of release end game tasks

src/auth/progress.auth.bearer.js, src/auth/progress.auth.form.js, src/auth/progress.auth.js, src/auth/progress.auth.sso.js, src/progress.js, src/progress.session.js
Support for OAuth using bearer token. JSDO with the changes can pass bearer token for login.
=> Added support for passing bearer token in Authorization header

packages/ng-datasource/package.json
=> Fixed some dependency issues

src/progress.session.js
Fixed an issue where I call invalidate() on the jsdosession too early.
=> Miscalled invalidate() too early in the authorization

package.json, packages/ng-datasource/package.json, packages/node/package.json, src/progress.util.js
Adding a change to remove the node-localstorage dependency.
=> Merging PR-121

packages/ng-datasource/package.json, packages/node/notice.txt, packages/node/package.json
cleaning up and removing base-64 from remaining package.json that was missing before. also removed it from notice.txt
=> remove base-64 from remaining packages

packages/node/test/regressions/ADAS-7282.js, packages/node/test/smoke.datasource.js, test/regressions/ADAS-7828.JFP.DATE.js
- [x ] Read our contributing guidelines: https://github.com/progress/JSDO/blob/master/contributing.md#contribute-to-the-code-base.
=> fix mocha tests to use oemobiledemo services

packages/node/notice.txt
=> official update from legal

packages/core/package.json
=> make jsdo 6.0.2 to fix build issue
